### ISSUE TITLE
[NOTICE] This application cannot tree shake icons fonts.

### ISSUE THREAD

**Issue by MacDeveloper1** [FaFre/flutter_material_design_icons#2]
I need to save/read icons to/from database. It is naturally to show icon I need to create an `IconData` class from JSON, i.e. that instance of `IconData` is not a constant.

```dart
IconData deserialize(JsonMap iconData) {
  return IconData(
    iconData['codePoint'],
    fontFamily: iconData['fontFamily'],
    fontPackage: iconData['fontPackage'],
    matchTextDirection: iconData['matchTextDirection'],
  );
}
```
So we have:

> This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:

P.S. Just to inform you. I expected that this package will save me. ;)
P.P.S. Also you use different name for `fontPackage` so my already saved icons are not shown because wrong package.

**Comment by FaFre** [comment]
Hello @MacDeveloper1 , thank you for opening this issue. 
Can you please elaborate more what your issue and proposed solution is?

I'm a bit confused, since I don't see the correlation to this package. When you dynamically create `IconData` you will need to compile with `--no-tree-shake-icons`. When you want to save icons to the database you can just iterate over the `MdiIcons.values` enum and get the corresponding icon via either icon name or maybe codepoint. Will also keep your database smaller and you can use the const `IconData` residing in the package.
